Feature/initial release
halloverden/symfony-oidc-client-bundle pull request #1
Opened 2020-07-31 13:05 UTC by tomme87

Initial release of oidc client bundle

2020-08-06 15:44 UTC, erichjsonfosse requested changes
As per conversation: Helpers folder should be moved to root

2020-08-06 15:44 UTC, erichjsonfosse commented on Token/AbstractToken.php
> +    $accessToken = new static();
Variable should be named $token in the abstract class

2020-08-10 12:07 UTC, tomme87 commented on composer.json
> +        "halloverden/symfony-security": "@dev",
Shoud not be @dev wait for new relase of halloverden/symfony-security and fix.

2020-08-10 12:36 UTC, tomme87 commented on composer.json
> +        "halloverden/symfony-security": "@dev",
Never mind. 1.4.0 should be fine for this.

2020-08-18 10:26 UTC, tomme87 commented on composer.json
> +        "halloverden/symfony-security": "^1.4",
might as well wait for halloverden/symfony-security 2.0 and use that before releasing this.

2020-08-19 15:11 UTC, merged